### PR TITLE
:sparkles: remove the need of global variable

### PR DESCRIPTION
**Pull request by fabienjuif**
My client had some issue streaming in parallels.

So I limited the variables scope :)

### CODE REVIEW

**Comment by fabienjuif** [comment]
For the ones who needs that version, this is published here : https://www.npmjs.com/package/stream-to-mongo-db-fabienjuif (based on this PR)

**Comment by AbdullahAli** [comment]
Thank you for the pull request

I am looking to refactor the code in the near future, feel free to submit anything you feel would be useful

Thank you for the work, merging it in now 👍

**Comment by AbdullahAli** [comment]
`1.4.0` is now live

**Comment by fabienjuif** [comment]
Thank you @AbdullahAli :)

**Pull request merged**
